<?php
declare(strict_types=1);header('Content-Type: application/json; charset=utf-8');ini_set('display_errors','0');error_reporting(E_ALL);set_time_limit(300);require __DIR__.'/../api/config.php';require __DIR__.'/includes/storage.php';require __DIR__.'/limpar_storage.php';
function j(array $d,int $s=200):void{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function adminOf(array $u):bool{$p=strtolower((string)($u['perfil']??$u['role']??$u['nivel']??''));return !empty($u['is_admin'])||!empty($u['admin'])||$p==='admin'||strtolower((string)($u['login']??''))==='admin';}
function cleanStr(string $s,int $max=255):string{return substr(trim($s),0,$max);}
function logProcess(string $storage,array $row):void{if(!is_dir($storage.'/logs'))@mkdir($storage.'/logs',0775,true);@file_put_contents($storage.'/logs/processamentos.jsonl',json_encode($row,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL,FILE_APPEND|LOCK_EX);}
try{
 $u=usuarioAtual();if(!$u)j(['ok'=>false,'error'=>'Sessão expirada.'],401);if($_SERVER['REQUEST_METHOD']!=='POST')j(['ok'=>false,'error'=>'Apenas POST é permitido.'],405);$tok=(string)($_POST['csrf_token']??'');if(!hash_equals((string)($_SESSION['csrf_token']??''),$tok))j(['ok'=>false,'error'=>'Token de segurança inválido.'],419);
 foreach(['locatario'=>'Locatário','endereco'=>'Endereço','contato'=>'Contato','data_locacao'=>'Data','metragem'=>'Metragem','sheet_name'=>'Planilha'] as $f=>$label)if(trim((string)($_POST[$f]??''))==='')j(['ok'=>false,'error'=>'Preencha o campo: '.$label.'.'],400);
 if(!isset($_FILES['source_file'])||($_FILES['source_file']['error']??1)!==UPLOAD_ERR_OK)j(['ok'=>false,'error'=>'Arquivo XLSX não recebido corretamente.'],400);$file=$_FILES['source_file'];if(strtolower(pathinfo((string)$file['name'],PATHINFO_EXTENSION))!=='xlsx')j(['ok'=>false,'error'=>'O arquivo precisa ser .xlsx.'],400);
 $storage=orcamentosStorage();if(!is_dir($storage))@mkdir($storage,0775,true);limparJobsAntigos($storage,7);$job=bin2hex(random_bytes(12));$jobDir=$storage.'/'.$job;if(!mkdir($jobDir,0775,true)&&!is_dir($jobDir))j(['ok'=>false,'error'=>'Não foi possível criar a pasta de processamento.'],500);
 $source=$jobDir.'/source.xlsx';if(!copy((string)$file['tmp_name'],$source))j(['ok'=>false,'error'=>'Não foi possível salvar a planilha.'],500);
 $providerIds=json_decode((string)($_POST['providers_json']??'[]'),true);if(!is_array($providerIds)||count($providerIds)!==3)j(['ok'=>false,'error'=>'Selecione os três prestadores.'],400);$pf=$storage.'/prestadores.json';$providers=is_file($pf)?json_decode((string)file_get_contents($pf),true):[];if(!is_array($providers))$providers=[];$selected=[];foreach($providerIds as $pid){$match=null;foreach($providers as $p)if((string)($p['id']??'')===(string)$pid)$match=$p;if(!$match)j(['ok'=>false,'error'=>'Prestador selecionado não encontrado.'],400);$selected[]=$match;}
 $images=[];$finfo=class_exists('finfo')?new finfo(FILEINFO_MIME_TYPE):null;for($i=1;$i<=3;$i++){if(isset($_FILES['imagem'.$i])&&($_FILES['imagem'.$i]['error']??1)===UPLOAD_ERR_OK){$it=$_FILES['imagem'.$i];$mime=$finfo?$finfo->file($it['tmp_name']):(string)($it['type']??'');$ext=$mime==='image/png'?'png':($mime==='image/jpeg'?'jpg':'');if($ext==='')j(['ok'=>false,'error'=>'A imagem do Orçamento '.$i.' deve ser PNG ou JPG.'],400);$target=$jobDir.'/imagem'.$i.'.'.$ext;copy($it['tmp_name'],$target);$images[(string)$i]=$target;}else{if(!empty($selected[$i-1]['assinatura'])){foreach(['png','jpg','jpeg'] as $e){$candidate=$storage.'/prestadores/'.$selected[$i-1]['id'].'.'.$e;if(is_file($candidate)){$images[(string)$i]=$candidate;break;}}}}}
 $dt=DateTime::createFromFormat('Y-m-d',(string)$_POST['data_locacao']);if(!$dt)j(['ok'=>false,'error'=>'Data inválida.'],400);$metr=(float)str_replace(',','.',(string)$_POST['metragem']);if($metr<0)j(['ok'=>false,'error'=>'Metragem inválida.'],400);
 $settings=json_decode((string)($_POST['signature_settings']??'{}'),true);if(!is_array($settings))$settings=[];$sf=$storage.'/config_gerador.json';if(is_file($sf)){$saved=json_decode((string)file_get_contents($sf),true);if(is_array($saved))$settings=array_merge($saved,$settings);} $settings=['height'=>max(80,min(320,(int)($settings['height']??$settings['signature_height']??150))),'gap'=>max(1,min(6,(int)($settings['gap']??$settings['signature_gap']??1))),'align'=>in_array($settings['align']??$settings['signature_align']??'left',['left','center','right'],true)?($settings['align']??$settings['signature_align']):'left'];
 $cfg=['source'=>$source,'job_dir'=>$jobDir,'sheet'=>cleanStr((string)$_POST['sheet_name']),'locatario'=>cleanStr((string)$_POST['locatario']),'endereco'=>cleanStr((string)$_POST['endereco']),'contato'=>cleanStr((string)$_POST['contato'],120),'data'=>$dt->format('d/m/Y'),'metragem'=>$metr,'images'=>$images,'providers'=>$selected,'signature_settings'=>$settings];$configPath=$jobDir.'/config.json';file_put_contents($configPath,json_encode($cfg,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT),LOCK_EX);
 $python='py -3';$script=__DIR__.'/python/processar_orcamento.py';$cmd=$python.' "'.str_replace('"','\\"',$script).'" "'.str_replace('"','\\"',$configPath).'"';$start=microtime(true);$lines=[];$code=1;exec($cmd.' 2>&1',$lines,$code);$out=trim(implode(PHP_EOL,$lines));$duration=(int)round((microtime(true)-$start)*1000);$res=null;foreach(array_reverse(preg_split('/\r\n|\r|\n/',$out)?:[]) as $line){$x=json_decode(trim((string)$line),true);if(is_array($x)){$res=$x;break;}}
 if(!is_array($res)||empty($res['ok'])){logProcess($storage,['created_at'=>date('d/m/Y H:i:s'),'usuario'=>$u['nome']??$u['login']??'','locatario'=>$cfg['locatario'],'status'=>'ERRO','duration_ms'=>$duration,'error'=>$res['error']??$out]);j(['ok'=>false,'error'=>$res['error']??'O processamento retornou erro.','details'=>$out],500);}
 $expected=['Planilha de Acionamento.xlsx','Orçamento.pdf','Orçamento 2.pdf','Orçamento 3.pdf'];foreach($expected as $n)if(!is_file($jobDir.'/'.$n))j(['ok'=>false,'error'=>'Arquivo não foi criado: '.$n],500);$zipPath=$jobDir.'/Folha_de_Calculo_Orcamentos_'.$job.'.zip';$zip=new ZipArchive();if($zip->open($zipPath,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)j(['ok'=>false,'error'=>'Não foi possível criar o ZIP.'],500);foreach($expected as $n)$zip->addFile($jobDir.'/'.$n,$n);$zip->close();
 $names=array_map(fn($p)=>(string)($p['nome']??''),$selected);$histFile=$storage.'/historico_orcamentos.json';$hist=is_file($histFile)?json_decode((string)file_get_contents($histFile),true):[];if(!is_array($hist))$hist=[];$hist[]= ['created_at'=>date('d/m/Y H:i:s'),'usuario'=>$u['nome']??$u['login']??'','locatario'=>$cfg['locatario'],'endereco'=>$cfg['endereco'],'prestadores'=>array_map(fn($p)=>['nome'=>$p['nome']??'','cpf'=>$p['cpf']??''], $selected),'download'=>'download.php?job='.$job,'job'=>$job];if(count($hist)>500)$hist=array_slice($hist,-500);file_put_contents($histFile,json_encode($hist,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT),LOCK_EX);logProcess($storage,['created_at'=>date('d/m/Y H:i:s'),'usuario'=>$u['nome']??$u['login']??'','locatario'=>$cfg['locatario'],'status'=>'OK','duration_ms'=>$duration,'message'=>'3 abas, 3 PDFs e ZIP gerados.']);
 j(['ok'=>true,'message'=>'3 abas, 3 PDFs e o ZIP foram gerados.','download'=>'download.php?job='.$job,'pdfs'=>['visualizar.php?job='.$job.'&file='.rawurlencode('Orçamento.pdf'),'visualizar.php?job='.$job.'&file='.rawurlencode('Orçamento 2.pdf'),'visualizar.php?job='.$job.'&file='.rawurlencode('Orçamento 3.pdf')]]);
}catch(Throwable $e){j(['ok'=>false,'error'=>'Erro interno no gerador.','details'=>$e->getMessage(),'file'=>$e->getFile(),'line'=>$e->getLine()],500);}
